name: star_walk
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.18.0
  intl_utils: ^2.8.5
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  provider: ^6.1.0
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  generate: true
  assets:
    - lib/res/icons/
    - lib/res/images/

flutter_intl:
  enabled: true
